#!/bin/bash


## Install the necessary packages to R and julia 

Rscript -e "install.packages( c('RSEIS', 'RPMG', 'Rwave'), dependencies = TRUE, repos='http://cran.us.r-project.org')"

julia << EOF  
    Pkg.update()
    Pkg.add("DSP")
    Pkg.add("DataFrames")
    Pkg.add("RCall")
    Pkg.add("Glob")
    Pkg.clone("https://github.com/anowacki/SAC.jl")
EOF
